version: '3.8'

services:
#  mongo:
#    image: mongo:latest
#    restart: always
#    ports:
#      - 27017:27017
#volumes:
#  data:
  jupyter-tensorflow:
    build:
      context: env
      dockerfile: env/tensorflow/Dockerfile
    environment:
      JUPYTER_TYPE: lab
      JUPYTER_BASE_URL: /jupyter
    ports:
      - "8888:8888"
    restart: always

    
