jwt:
  tokenSecret: QAZwsx123
  tokenExpiresInMillis: 3600000 #1h

oauth2:
  # After successfully authenticating with the OAuth2 Provider,
  # we'll be generating an auth token for the user and sending the token to the
  # redirectUri mentioned by the client in the /oauth2/authorize request.
  # We're not using cookies because they won't work well in mobile clients.
  authorizedRedirectUris:
    - http://localhost:4200/oauth2/redirect

feign:
  client:
    config:
      default:
        loggerLevel: basic
        readTimeout: 5000
        connectTimeout: 5000

server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: trader_core
  session:
    mongodb:
      collection-name: sessions
    store-type: mongodb
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
            clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
            redirectUri: "http://localhost:4200/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 1254079278109916
            clientSecret: e745bee31c8601eb242e27a4b26e8d2f
            redirectUri: "http://localhost:4200/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: d3e47fc2ddd966fa4352
            clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
            redirectUri: "http://localhost:4200/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

logging:
  level:
    root: info

routes:
  publicRoutes:
    - "/api/login/**"
    - "/api/logout/**"
    - "/api/signup/**"
    - "/websocket/**"

rabbitmq:
  relayHost: localhost
  relayPort: 61613

notification:
  destinations:
    TICKER_EVENT: "'/topic/' + asset + '-ticker'"

binance:
  url: wss://api.binance.com/
  apiKey: Zqxi5MgLBbAHQa20Lp9E9xQEW5BmI3sxzpR1se3zHaoSpmoO2thq5q7z8Zt9xm2v
  secretKey: EApcbO0IZx72dPnbACq3ND8VoGH2mTJ031Wncb8hDaJ3nNews7O1yNneAgI2BUDS
  useTestnet: false
  useTestnetStreaming: false
  blacklist:
    - NFT
  assets:
    1INCH:
      icon: 8104
      symbol: 1INCHUSDT
      fullName: 1inch
    AAVE:
      icon: 7278
      symbol: AAVEUSDT
      fullName: Aave
    ADA:
      icon: 2010
      symbol: ADAUSDT
      fullName: Cardano
    AKRO:
      icon: 4134
      symbol: AKROUSDT
      fullName: Akropolis
    ALGO:
      icon: 4030
      symbol: ALGOUSDT
      fullName: Algorand
    ALICE:
      icon: 8766
      symbol: ALICEUSDT
      fullName: MyNeighborAlice
    AlPHA:
      icon: 7232
      symbol: ALPHAUSDT
      fullName: Alpha Finance Lab
    ANKR:
      icon: 3783
      symbol: ANKRUSDT
      fullName: Ankr
    ATOM:
      icon: 3794
      symbol: ATOMUSDT
      fullName: Cosmos
    AVAX:
      icon: 5805
      symbol: AVAXUSDT
      fullName: Avalanche
    AXS:
      icon: 6783
      symbol: AXSUSDT
      fullName: Axie Infinity
    BAKE:
      icon: 7064
      symbol: BAKEUSDT
      fullName: BakeryToken
    BAL:
      icon: 5728
      symbol: BALUSDT
      fullName: Balanceer
    BAND:
      icon: 4679
      symbol: BANDUSDT
      fullName: Band Protocol
    BAT:
      icon: 1697
      symbol: BATUSDT
      fullName: Basic Attention Token
    BCH:
      icon: 1831
      symbol: BCHUSDT
      fullName: Bitcoin Cash
    BEL:
      icon: 6928
      symbol: BEL
      fullName: Bella Protocol
    BLZ:
      icon: 2505
      symbol: BLZUSDT
      fullName: Bluzelle
    BTC:
      icon: 4023
      symbol: BTCUSDT
      fullName: Bitcoin
    BTS:
      icon: 463
      symbol: BTSUSDT
      fullName: BitShares
    BTT:
      icon: 3718
      symbol: BTTUSDT
      fullName: BitTorrent
    BZR:
      icon: 5810
      symbol: BZRXUSDT
      fullName: bZx Protocol
    CELR:
      icon: 3814
      symbol: CELRUSDT
      fullName: Celer Network
    CHR:
      icon: 3978
      symbol: CHRUSDT
      fullName: Chromia
    CHZ:
      icon: 4066
      symbol: CHZUSDT
      fullName: Chilliz
    COMP:
      icon: 5692
      symbol: COMPUSDT
      fullName: Compound
    COTI:
      icon: 3992
      symbol: COTIUSDT
      fullName: COTI
    CRV:
      icon: 6538
      symbol: CRVUSDT
      fullName: Curve DAO Token
    CTK:
      icon: 4807
      symbol: CTKUSDT
      fullName: CertiK
    CVC:
      icon: 1816
      symbol: CVCUSDT
      fullName: Civic
    DASH:
      icon: 131
      symbol: DASHUSDT
      fullName: Dash
    DEFI:
      icon: 4276
      symbol: DEFIUSDT
      fullName: Defi
    DENT:
      icon: 1886
      symbol: DENTUSDT
      fullName: Dent
    DGB:
      icon: 109
      symbol: DGBUSDT
      fullName: DigiByte
    DIT:
      icon: 3264
      symbol: DITUSDT
      fullName: Digital Insurance Token
    DODO:
      icon: 7224
      symbol: DODOUSDT
      fullName: DODO
    DOGE:
      icon: 74
      symbol: DOGEUSDT
      fullName: Dogecoin
    EGLD:
      icon: 6892
      symbol: EGLDUSDT
      fullName: Elrond
    ENJ:
      icon: 2130
      symbol: ENJUSDT
      fullName: Enjin Coin
    EOS:
      icon: 1765
      symbol: EOSUSDT
      fullName: EOS
    ETC:
      icon: 1321
      symbol: ETCUSDT
      fullName: Etherium Classic
    ETH:
      icon: 1027
      symbol: ETHUSDT
      fullName: Ethereum
    FIL:
      icon: 2280
      symbol: FILUSDT
      fullName: Filecoin
    FLM:
      icon: 7150
      symbol: FLMUSDT
      fullName: Flamingo
    FTM:
      icon: 3513
      symbol: FTMUSDT
      fullName: Fantom
    GRT:
      icon: 6719
      symbol: GRTUSDT
      fullName: The Graph
    HBAR:
      icon: 4642
      symbol: HBARUSDT
      fullName: Hedera Hashgraph
    HNT:
      icon: 5665
      symbol: HNTUSDT
      fullName: Helium
    HOT:
      icon: 2682
      symbol: HOTUSDT
      fullName: Holo
    ICP:
      icon: 8916
      symbol: ICPUSDT
      fullName: Internet Computer
    ICX:
      icon: 2099
      symbol: ICXUSDT
      fullName: ICON
    IOS:
      icon: 2405
      symbol: IOSTUSDT
      fullName: IOST
    IOTA:
      icon: 1720
      symbol: IOTAUSDT
      fullName: MIOTA
    KAVA:
      icon: 4846
      symbol: KAVAUSDT
      fullName: KAVA
    KNC:
      icon: 9444
      symbol: KNCUSDT
      fullName: Kyber Network Crystal v2
    KSM:
      icon: 5034
      symbol: KSMUSDT
      fullName: Kusama
    LINA:
      icon: 7102
      symbol: LINAUSDT
      fullName: Linear
    LINK:
      icon: 1975
      symbol: LINKUSDT
      fullName: Chainlink
    LIT:
      icon: 6833
      symbol: LITUSDT
      fullName: Litentry
    LRC:
      icon: 1934
      symbol: LRCUSDT
      fullName: Loopring
    LTC:
      icon: 2
      symbol: LTCUSDT
      fullName: Litecoin
    LUNA:
      icon: 4172
      symbol: LUNAUSDT
      fullName: Terra
    MANA:
      icon: 1966
      symbol: MANAUSDT
      fullName: Decentraland
    MATIC:
      icon: 3890
      symbol: MATICUSDT
      fullName: Polygon
    MKR:
      icon: 1518
      symbol: MKRUSDT
      fullName: Maker
    MTL:
      icon: 1788
      symbol: MTLUSDT
      fullName: Metal
    NEAR:
      icon: 6535
      symbol: NEARUSDT
      fullName: NEAR Protocol
    NEO:
      icon: 1376
      symbol: NEOUSDT
      fullName: Neo
    NKN:
      icon: 2780
      symbol: NKNUSDT
      fullName: NKN
    OCEAN:
      icon: 3911
      symbol: OCEANUSDT
      fullName: Ocean Protocol
    OGN:
      icon: 5117
      symbol: OGNUSDT
      fullName: Origin Protocol
    OMG:
      icon: 8104
      symbol: OMGUSDT
      fullName: OMG Network
    ONE:
      icon: 3945
      symbol: ONEUSDT
      fullName: Harmony
    ONT:
      icon: 2566
      symbol: ONTUSDT
      fullName: Ontology
    QTUM:
      icon: 1684
      symbol: QTUMUSDT
      fullName: Qtum
    REEF:
      icon: 6951
      symbol: REEFUSDT
      fullName: Reef
    REN:
      icon: 2539
      symbol: RENUSDT
      fullName: Ren
    RLC:
      icon: 1637
      symbol: RLCUSDT
      fullName: iExec RLC
    RSR:
      icon: 3964
      symbol: RSRUSDT
      fullName: Reserve Rights
    RUNE:
      icon: 4157
      symbol: RUNEUSDT
      fullName: THORChain
    RVN:
      icon: 2577
      symbol: RVNUSDT
      fullName: Ravecoin
    SAND:
      icon: 6210
      symbol: SANDUSDT
      fullName: The Sandbox
    SC:
      icon: 1042
      symbol: SCUSDT
      fullName: Siacoin
    SFP:
      icon: 8119
      symbol: SFPUSDT
      fullName: SafePal
    SHIB:
      icon: 5994
      symbol: 1000SHIBUSDT
      fullName: SHIBA INU
    SKL:
      icon: 5691
      symbol: SKLUSDT
      fullName: SKALE Network
    SNX:
      icon: 2586
      symbol: SNXUSDT
      fullName: Synthetix
    SRM:
      icon: 6187
      symbol: SRMUSDT
      fullName: Serum
    STMX:
      icon: 2297
      symbol: STMXUSDT
      fullName: StormX
    STORJ:
      icon: 1772
      symbol: STORJUSDT
      fullName: Storj
    SUSHI:
      icon: 6758
      symbol: SUSHIUSDT
      fullName: SushiSwap
    SXP:
      icon: 4279
      symbol: SXPUSDT
      fullName: Swipe
    THETA:
      icon: 2416
      symbol: THETAUSDT
      fullName: THETA
    TOMO:
      icon: 2570
      symbol: TOMOUSDT
      fullName: TomoChain
    TRB:
      icon: 4944
      symbol: TRBUSDT
      fullName: Tellor
    TRX:
      icon: 1958
      symbol: TRXUSDT
      fullName: TRON
    UNFI:
      icon: 7672
      symbol: UNFIUSDT
      fullName: Unifi Protocol DAO
    UNI:
      icon: 7083
      symbol: UNIUSDT
      fullName: Uniswap
    VET:
      icon: 3077
      symbol: VETUSDT
      fullName: VeChain
    XEM:
      icon: 873
      symbol: XEMUSDT
      fullName: NEM
    XLM:
      icon: 512
      symbol: XLMUSDT
      fullName: Stellar
    XMR:
      icon: 328
      symbol: XMRUSDT
      fullName: Monero
    XTZ:
      icon: 2011
      symbol: XTZUSDT
      fullName: Tezos
    YFI:
      icon: 5864
      symbol: YFIUSDT
      fullName: yearn.finance
    YFII:
      icon: 5957
      symbol: YFIIUSDT
      fullName: DFI.Money
    ZEC:
      icon: 1437
      symbol: ZECUSDT
      fullName: Zcash
    ZEN:
      icon: 1698
      symbol: ZENUSDT
      fullName: Horizen
    ZIL:
      icon: 2469
      symbol: ZILUSDT
      fullName: Zilliqa
    ZRX:
      icon: 1896
      symbol: ZRXUSDT
      fullName: Ox
    XEC:
      icon: 10791
      symbol: 1000XECUSDT
      fullName: eCash
    C98:
      icon: 10903
      symbol: C98USDT
      fullName: Coin98
    KEEP:
      icon: 5566
      symbol: KEEPUSDT
      fullName: Keep Network4
    AR:
      icon: 5632
      symbol: ARUSDT
      fullName: Arweave
    CELO:
      icon: 5567
      symbol: CELOUSDT
      fullName: Celo
    GTC:
      icon: 10052
      symbol: GTCUSDT
      fullName: Gitcoin
    TLM:
      icon: 9119
      symbol: TLMUSDT
      fullName: Alien Worlds
    AUDIO:
      icon: 7455
      symbol: AUDIOUSDT
      fullName: Audius
    RAY:
      icon: 8526
      symbol: RAYUSDT
      fullName: Raydium
    DOT:
      icon: 6636
      symbol: DOTUSDT
      fullName: Polkadot
    BNB:
      icon: 1839
      symbol: BNBUSDT
      fullName: Binance Coin
    SOL:
      icon: 5426
      symbol: SOLUSDT
      fullName: Solana
    WAVES:
      icon: 1274
      symbol: WAVESUSDT
      fullName: Waves
    MASK:
      icon: 8536
      symbol: MASKUSDT
      fullName: Mask Network
    XRP:
      icon: 52
      symbol: XRPUSDT
      fullName: XRP
    DYDX:
      icon: 11156
      symbol: DYDXUSDT
      fullName: dYdX
    ATA:
      icon: 10188
      symbol: ATAUSDT
      fullName: Automata Network
    IOTX:
      icon: 2777
      symbol: IOTXUSDT
      fullName: IoTeX
    GALA:
      icon: 7080
      symbol: GALAUSDT
      fullName: Gala
    USDT:
      icon: 825
      symbol: USDT
      fullName: Tether
    NFT:
      icon: 9816
      symbol: NFTUSDT
      fullName: APENNFT
    LPT:
      icon: 3640
      symbol: LPTUSDT
      fullName: Livepeer
