jwt:
  tokenSecret: QAZwsx123
  tokenExpiresInMillis: 3600000 #1h

oauth2:
  # After successfully authenticating with the OAuth2 Provider,
  # we'll be generating an auth token for the user and sending the token to the
  # redirectUri mentioned by the client in the /oauth2/authorize request.
  # We're not using cookies because they won't work well in mobile clients.
  authorizedRedirectUris:
    - http://localhost:4200/oauth2/redirect

feign:
  client:
    config:
      default:
        loggerLevel: basic
        readTimeout: 5000
        connectTimeout: 5000

server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: crypto_core
  session:
    mongodb:
      collection-name: sessions
    store-type: mongodb
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
            clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
            redirectUri: "http://localhost:4200/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 1254079278109916
            clientSecret: e745bee31c8601eb242e27a4b26e8d2f
            redirectUri: "http://localhost:4200/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: d3e47fc2ddd966fa4352
            clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
            redirectUri: "http://localhost:4200/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

logging:
  level:
    root: info

routes:
  publicRoutes:
    - "/api/login/**"
    - "/api/logout/**"
    - "/api/signup/**"
    - "/websocket/**"

rabbitmq:
  relayHost: localhost
  relayPort: 61613

notification:
  destinations:
    TICKER_EVENT: "'/topic/' + symbol + '-ticker'"

binance:
  url: wss://api.binance.com/
  apiKey: Zqxi5MgLBbAHQa20Lp9E9xQEW5BmI3sxzpR1se3zHaoSpmoO2thq5q7z8Zt9xm2v
  secretKey: EApcbO0IZx72dPnbACq3ND8VoGH2mTJ031Wncb8hDaJ3nNews7O1yNneAgI2BUDS
  useTestnet: false
  useTestnetStreaming: false
  blacklist:
    - NFT
  assets:
    1INCH:
      icon: 8104
      coin: 1INCHUSDT
      name: 1inch
    AAVE:
      icon: 7278
      coin: AAVEUSDT
      name: Aave
    ADA:
      icon: 2010
      coin: ADAUSDT
      name: Cardano
    AKRO:
      icon: 4134
      coin: AKROUSDT
      name: Akropolis
    ALGO:
      icon: 4030
      coin: ALGOUSDT
      name: Algorand
    ALICE:
      icon: 8766
      coin: ALICEUSDT
      name: MyNeighborAlice
    AlPHA:
      icon: 7232
      coin: ALPHAUSDT
      name: Alpha Finance Lab
    ANKR:
      icon: 3783
      coin: ANKRUSDT
      name: Ankr
    ATOM:
      icon: 3794
      coin: ATOMUSDT
      name: Cosmos
    AVAX:
      icon: 5805
      coin: AVAXUSDT
      name: Avalanche
    AXS:
      icon: 6783
      coin: AXSUSDT
      name: Axie Infinity
    BAKE:
      icon: 7064
      coin: BAKEUSDT
      name: BakeryToken
    BAL:
      icon: 5728
      coin: BALUSDT
      name: Balanceer
    BAND:
      icon: 4679
      coin: BANDUSDT
      name: Band Protocol
    BAT:
      icon: 1697
      coin: BATUSDT
      name: Basic Attention Token
    BCH:
      icon: 1831
      coin: BCHUSDT
      name: Bitcoin Cash
    BEL:
      icon: 6928
      coin: BEL
      name: Bella Protocol
    BLZ:
      icon: 2505
      coin: BLZUSDT
      name: Bluzelle
    BTC:
      icon: 4023
      coin: BTCUSDT
      name: Bitcoin
    BTS:
      icon: 463
      coin: BTSUSDT
      name: BitShares
    BTT:
      icon: 3718
      coin: BTTUSDT
      name: BitTorrent
    BZR:
      icon: 5810
      coin: BZRXUSDT
      name: bZx Protocol
    CELR:
      icon: 3814
      coin: CELRUSDT
      name: Celer Network
    CHR:
      icon: 3978
      coin: CHRUSDT
      name: Chromia
    CHZ:
      icon: 4066
      coin: CHZUSDT
      name: Chilliz
    COMP:
      icon: 5692
      coin: COMPUSDT
      name: Compound
    COTI:
      icon: 3992
      coin: COTIUSDT
      name: COTI
    CRV:
      icon: 6538
      coin: CRVUSDT
      name: Curve DAO Token
    CTK:
      icon: 4807
      coin: CTKUSDT
      name: CertiK
    CVC:
      icon: 1816
      coin: CVCUSDT
      name: Civic
    DASH:
      icon: 131
      coin: DASHUSDT
      name: Dash
    DEFI:
      icon: 4276
      coin: DEFIUSDT
      name: Defi
    DENT:
      icon: 1886
      coin: DENTUSDT
      name: Dent
    DGB:
      icon: 109
      coin: DGBUSDT
      name: DigiByte
    DIT:
      icon: 3264
      coin: DITUSDT
      name: Digital Insurance Token
    DODO:
      icon: 7224
      coin: DODOUSDT
      name: DODO
    DOGE:
      icon: 74
      coin: DOGEUSDT
      name: Dogecoin
    EGLD:
      icon: 6892
      coin: EGLDUSDT
      name: Elrond
    ENJ:
      icon: 2130
      coin: ENJUSDT
      name: Enjin Coin
    EOS:
      icon: 1765
      coin: EOSUSDT
      name: EOS
    ETC:
      icon: 1321
      coin: ETCUSDT
      name: Etherium Classic
    ETH:
      icon: 1027
      coin: ETHUSDT
      name: Ethereum
    FIL:
      icon: 2280
      coin: FILUSDT
      name: Filecoin
    FLM:
      icon: 7150
      coin: FLMUSDT
      name: Flamingo
    FTM:
      icon: 3513
      coin: FTMUSDT
      name: Fantom
    GRT:
      icon: 6719
      coin: GRTUSDT
      name: The Graph
    HBAR:
      icon: 4642
      coin: HBARUSDT
      name: Hedera Hashgraph
    HNT:
      icon: 5665
      coin: HNTUSDT
      name: Helium
    HOT:
      icon: 2682
      coin: HOTUSDT
      name: Holo
    ICP:
      icon: 8916
      coin: ICPUSDT
      name: Internet Computer
    ICX:
      icon: 2099
      coin: ICXUSDT
      name: ICON
    IOS:
      icon: 2405
      coin: IOSTUSDT
      name: IOST
    IOTA:
      icon: 1720
      coin: IOTAUSDT
      name: MIOTA
    KAVA:
      icon: 4846
      coin: KAVAUSDT
      name: KAVA
    KNC:
      icon: 9444
      coin: KNCUSDT
      name: Kyber Network Crystal v2
    KSM:
      icon: 5034
      coin: KSMUSDT
      name: Kusama
    LINA:
      icon: 7102
      coin: LINAUSDT
      name: Linear
    LINK:
      icon: 1975
      coin: LINKUSDT
      name: Chainlink
    LIT:
      icon: 6833
      coin: LITUSDT
      name: Litentry
    LRC:
      icon: 1934
      coin: LRCUSDT
      name: Loopring
    LTC:
      icon: 2
      coin: LTCUSDT
      name: Litecoin
    LUNA:
      icon: 4172
      coin: LUNAUSDT
      name: Terra
    MANA:
      icon: 1966
      coin: MANAUSDT
      name: Decentraland
    MATIC:
      icon: 3890
      coin: MATICUSDT
      name: Polygon
    MKR:
      icon: 1518
      coin: MKRUSDT
      name: Maker
    MTL:
      icon: 1788
      coin: MTLUSDT
      name: Metal
    NEAR:
      icon: 6535
      coin: NEARUSDT
      name: NEAR Protocol
    NEO:
      icon: 1376
      coin: NEOUSDT
      name: Neo
    NKN:
      icon: 2780
      coin: NKNUSDT
      name: NKN
    OCEAN:
      icon: 3911
      coin: OCEANUSDT
      name: Ocean Protocol
    OGN:
      icon: 5117
      coin: OGNUSDT
      name: Origin Protocol
    OMG:
      icon: 8104
      coin: OMGUSDT
      name: OMG Network
    ONE:
      icon: 3945
      coin: ONEUSDT
      name: Harmony
    ONT:
      icon: 2566
      coin: ONTUSDT
      name: Ontology
    QTUM:
      icon: 1684
      coin: QTUMUSDT
      name: Qtum
    REEF:
      icon: 6951
      coin: REEFUSDT
      name: Reef
    REN:
      icon: 2539
      coin: RENUSDT
      name: Ren
    RLC:
      icon: 1637
      coin: RLCUSDT
      name: iExec RLC
    RSR:
      icon: 3964
      coin: RSRUSDT
      name: Reserve Rights
    RUNE:
      icon: 4157
      coin: RUNEUSDT
      name: THORChain
    RVN:
      icon: 2577
      coin: RVNUSDT
      name: Ravecoin
    SAND:
      icon: 6210
      coin: SANDUSDT
      name: The Sandbox
    SC:
      icon: 1042
      coin: SCUSDT
      name: Siacoin
    SFP:
      icon: 8119
      coin: SFPUSDT
      name: SafePal
    SHIB:
      icon: 5994
      coin: 1000SHIBUSDT
      name: SHIBA INU
    SKL:
      icon: 5691
      coin: SKLUSDT
      name: SKALE Network
    SNX:
      icon: 2586
      coin: SNXUSDT
      name: Synthetix
    SRM:
      icon: 6187
      coin: SRMUSDT
      name: Serum
    STMX:
      icon: 2297
      coin: STMXUSDT
      name: StormX
    STORJ:
      icon: 1772
      coin: STORJUSDT
      name: Storj
    SUSHI:
      icon: 6758
      coin: SUSHIUSDT
      name: SushiSwap
    SXP:
      icon: 4279
      coin: SXPUSDT
      name: Swipe
    THETA:
      icon: 2416
      coin: THETAUSDT
      name: THETA
    TOMO:
      icon: 2570
      coin: TOMOUSDT
      name: TomoChain
    TRB:
      icon: 4944
      coin: TRBUSDT
      name: Tellor
    TRX:
      icon: 1958
      coin: TRXUSDT
      name: TRON
    UNFI:
      icon: 7672
      coin: UNFIUSDT
      name: Unifi Protocol DAO
    UNI:
      icon: 7083
      coin: UNIUSDT
      name: Uniswap
    VET:
      icon: 3077
      coin: VETUSDT
      name: VeChain
    XEM:
      icon: 873
      coin: XEMUSDT
      name: NEM
    XLM:
      icon: 512
      coin: XLMUSDT
      name: Stellar
    XMR:
      icon: 328
      coin: XMRUSDT
      name: Monero
    XTZ:
      icon: 2011
      coin: XTZUSDT
      name: Tezos
    YFI:
      icon: 5864
      coin: YFIUSDT
      name: yearn.finance
    YFII:
      icon: 5957
      coin: YFIIUSDT
      name: DFI.Money
    ZEC:
      icon: 1437
      coin: ZECUSDT
      name: Zcash
    ZEN:
      icon: 1698
      coin: ZENUSDT
      name: Horizen
    ZIL:
      icon: 2469
      coin: ZILUSDT
      name: Zilliqa
    ZRX:
      icon: 1896
      coin: ZRXUSDT
      name: Ox
    XEC:
      icon: 10791
      coin: 1000XECUSDT
      name: eCash
    C98:
      icon: 10903
      coin: C98USDT
      name: Coin98
    KEEP:
      icon: 5566
      coin: KEEPUSDT
      name: Keep Network4
    AR:
      icon: 5632
      coin: ARUSDT
      name: Arweave
    CELO:
      icon: 5567
      coin: CELOUSDT
      name: Celo
    GTC:
      icon: 10052
      coin: GTCUSDT
      name: Gitcoin
    TLM:
      icon: 9119
      coin: TLMUSDT
      name: Alien Worlds
    AUDIO:
      icon: 7455
      coin: AUDIOUSDT
      name: Audius
    RAY:
      icon: 8526
      coin: RAYUSDT
      name: Raydium
    DOT:
      icon: 6636
      coin: DOTUSDT
      name: Polkadot
    BNB:
      icon: 1839
      coin: BNBUSDT
      name: Binance Coin
    SOL:
      icon: 5426
      coin: SOLUSDT
      name: Solana
    WAVES:
      icon: 1274
      coin: WAVESUSDT
      name: Waves
    MASK:
      icon: 8536
      coin: MASKUSDT
      name: Mask Network
    XRP:
      icon: 52
      coin: XRPUSDT
      name: XRP
    DYDX:
      icon: 11156
      coin: DYDXUSDT
      name: dYdX
    ATA:
      icon: 10188
      coin: ATAUSDT
      name: Automata Network
    IOTX:
      icon: 2777
      coin: IOTXUSDT
      name: IoTeX
    GALA:
      icon: 7080
      coin: GALAUSDT
      name: Gala
    USDT:
      icon: 825
      coin: USDT
      name: Tether
    NFT:
      icon: 9816
      coin: NFTUSDT
      name: APENNFT
